//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTATRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tin
    {
        public int MaTin { get; set; }
        public string Tieude { get; set; }
        public string Anh1 { get; set; }
        public string Anh2 { get; set; }
        public string Anh3 { get; set; }
        public string Anh4 { get; set; }
        public string Anh5 { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
        public Nullable<int> Luotxem { get; set; }
        public string Noidung { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
